module.exports = {
    SCHEMAS:{
        FOOTWEAR:'footwear',
        INVOICE: 'invoice',
        CONFIG_LISTS:'config_lists',
        TRADER_FINANCES: 'trader_finances'
    },
    STATUS_CODES:{
        SUCCESS:200,
        SUCCESS2:201,
        SERVER_CRASH:500,
        FILE_NOT_FOUND:404,
        NOT_FOUND:404
    },
    ROUTES:{
        MY_API:'/my_api',
        DIRECT_CHANGE:'/direct_change',
        ROOT:'/',
        GET_CONFIF_LISTS:'/get_config_lists',
        INVOICE:{
            SAVE_INVOICE:'/saveInvoice',
            FETCH_INVOICES:'/fetchInvoices'
        },
        PRODUCT:{
            addFootwear:'/add_footwear',
            applyChanges:'/applyChanges',
            VIEW_ALL_FOOTWEARS:'/view_all_footwears',
            FILTER_FOOTWEARS:'/filter_footwears',
            VIEW_45_PRODUCTS:'/view_45_products',
            VIEW_BY_interest:'/view_by_interest',
            VIEW_BY_NAME:'/view_by_name',
            VIEW_BY_CATEGORY:'/view_by_category',
            VIEW_BY_CATEGORIES:'/view_by_categories',
            VIEW_BY_PRICE:'/view_by_price',
            VIEW_BY_RATING:'/view_by_rating',
            VIEW_BY_NAME_CATEGORY:'/view_by_name_category',
            VIEW_BY_NAME_CATEGORIES:'/view_by_name_categories',
            VIEW_BY_PRICE_CATEGORIES:'/view_by_price_categories',
            VIEW_BY_FOOTWEAR_ID:'/view_by_footwear_id',
            VIEW_ALL_REVIEWS:'/view_all_reviews',
            SEARCH_IN_REVIEWS:'/search_in_reviews',
            RATE_PRODUCT:'/rate_product',
            REVIEW_PRODUCT:'/review_product',
            EDIT_RATING:'/edit_rating',
            EDIT_REVIEW:'/edit_review',
            UPDATE_PRODUCT:'/update_product',
            UPDATE_QUANTITY:'/update_quantity',
            DELETE_PRODUCT:'/delete_product',
        },
    }
}